import type { Metadata } from "next";

import Sidebar from "@/components/sidebar";

import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "IDEC UI Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex">
        <div className="hidden lg:flex">
          <Sidebar />
        </div>
        <main className="py-[10px] pl-[10px] lg:pl-[320px] pr-[10px] lg:pr-[20px] w-full lg:py-[20px] overflow-y-auto">
          <div className="mb-4 flex gap-2 lg:hidden items-center justify-center">
            <Header />
          </div>
          {children}
        </main>
      </div>
      <Toaster />
    </>
  );
}
