import FooterIdec from "@/components/footer-idec";
import HeaderIdec from "@/components/header-idec";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "IDEC Home page",
  description: "Generated by create next app",
};
export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderIdec />
      {children}
      <FooterIdec />
    </>
  );
}
