import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "@/components/sidebar";
import Banner from "@/components/banner";
import { Poppins } from "next/font/google";
import Image from "next/image";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "IDEC UI Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-gray-100`}>
        <div className="flex">
          <div className="hidden lg:flex">
            <Sidebar />
          </div>
          <main className="py-[10px] pl-[10px] lg:pl-[320px] pr-[10px] lg:pr-[20px] lg:py-[20px] overflow-y-auto">
            <div className="mb-4 flex gap-2 lg:hidden items-center justify-center">
              <Image
                src="/images/logo.jpg"
                width={150}
                height={100}
                alt="Picture of the author"
                className="w-[150px]"
              />
              <h2 className="font-bold text-2xl">UI Components</h2>
            </div>
            <div className="mb-10">
              <Banner />
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
